os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/cache/GCloud.ini")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/tbslog")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/ca-bundle.pem")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/cacheFile.txt")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/login-identifier.txt")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/vmpcloudconfig.json")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/ProgramBinaryCache")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_temp")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_res.eifs")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1375135419_47_0.13.0.11098_20190617165748_1981158817_cures.ifs.res")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir")
  os.remove("/data/data/com.tencent.iglite/app_appcache")
  os.remove("/data/data/com.tencent.iglite/app_bugly")
  os.remove("/data/data/com.tencent.iglite/app_crashrecord")
  os.remove("/data/data/com.tencent.iglite/cache")
  os.remove("/data/data/com.tencent.iglite/code_cache")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/cache")
  os.remove("/storage/emulated/0/tencent")
  os.remove("/storage/emulated/0/MidasOverse")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/tbslog")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/login-identifier.txt")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/cacheFile.txt")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/vmpcloudconfig.json")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AntiCheat.ini")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/IGH5CachePluginConfig.ini")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/cache")
  os.remove("/storage/emulated/0/tencent")
  os.remove("/storage/emulated/0/MidasOverse")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/tbslog")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/login-identifier.txt")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/cacheFile.txt")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/vmpcloudconfig.json")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AntiCheat.ini")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/IGH5CachePluginConfig.ini")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/cache")
  os.remove("/storage/emulated/0/tencent")
  os.remove("/storage/emulated/0/MidasOverse")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/tbslog")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/login-identifier.txt")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/cacheFile.txt")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/vmpcloudconfig.json")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AntiCheat.ini")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/IGH5CachePluginConfig.ini")
  os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/cache")
os.remove("/storage/emulated/0/tencent")
os.remove("/storage/emulated/0/MidasOverse")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/tbslog")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/login-identifier.txt")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/cacheFile.txt")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/vmpcloudconfig.json")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords")
os.remove("/storage/emulated/0/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AntiCheat.ini")
os.remove("/stroage/emulated/Android/data/com.tencent.iglite/cache/")
os.remove("/storage/emulated/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs")
os.remove("/storage/emulated/Android/data/com.tencent.iglite/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo")
os.remove("/storage/emulated/Android/data/com.tencent.iglite/files/ca-bundle.pem")

  function main()
  Amenu = gg.choice({
    "🏠One Click Lobby",
    "🎮Ond Click Game",
    "🙎‍♂️Colour",
    "🔙Keluar",
}, nil, (os.date("Farzhad | Simpel Fast Cheat\n%d %B %Y %H:%M%p")))
  if Amenu == 1 then
    A()
  end
  if Amenu == 2 then
    B()
  end
  if Amenu == 3 then
     C()
     end
  if Amenu == 4 then
     D()
     end
  Pharao = -1
end

function A()
gg.clearResults()
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber( "3.5;1;200;20::999", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber( "3.5;1;200;20", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(300)
gg.editAll( "1.0e20", gg.TYPE_FLOAT)
gg.clearResults()
gg.toast("Aimbot") 
gg.clearResults()
gg.setRanges(gg.REGION_C_DATA) 
gg.searchNumber('-2.786982e28;-3.7444097e28;-1.1368837e-13::', gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1) 
gg.searchNumber('-3.7444097e28', gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1) 
gg.getResults(10) 
gg.editAll('0', gg.TYPE_FLOAT) 
gg.clearResults() 
gg.setRanges(gg.REGION_C_DATA) 
gg.searchNumber('-2.8111605e28;-3.7444097e28;-1.1144502e28;128.0::', gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1) 
gg.searchNumber('-1.1144502e28', gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1) 
gg.getResults(10) 
gg.editAll('0', gg.TYPE_FLOAT) 
gg.clearResults() 
gg.setRanges(gg.REGION_C_DATA) 
gg.searchNumber('-6.1549454e27;1.8638966e-20;-1.1144502e28;0::', gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1) 
gg.searchNumber('-1.1144502e28', gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1) 
gg.getResults(10) 
gg.editAll('0', gg.TYPE_FLOAT) 
gg.clearResults() 
gg.setRanges(gg.REGION_C_DATA) 
gg.searchNumber('-1.238.624e28;-1.4239333e28;-1.1144502e28;-1.8331474e27;-    7.1608877e24::', gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1) 
gg.searchNumber('-1.1144502e28', gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1) 
gg.getResults(20) 
gg.editAll('90', gg.TYPE_FLOAT) 
gg.toast("No recoil") 
gg.clearResults() 
end

function B()
gg.clearResults()
gg.setRanges(gg.REGION_C_BSS)
 gg.searchNumber("2048D;4D;1F;1F;1D:30", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.getResultsCount()
gg.clearResults()
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber("3000;5000;1024;1000::", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(3472849)
gg.editAll("99999", gg.TYPE_FLOAT)
gg.clearResults()
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber("88.50576019287F;87.27782440186F;-100.91194152832F;1F::13", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.searchNumber("88.50576019287F;87.27782440186F;1F", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(1000, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll("1.96875;1.96875;999;1.96875;1.96875;999", gg.TYPE_FLOAT)
gg.toast("Antena ")
gg.clearResults()
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber("23;25;30.5", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.searchNumber("25;30.5", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100)
gg.editAll("2000", gg.TYPE_FLOAT)
gg.clearResults()
gg.toast("Headshot")
gg.clearResults()
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber( "3.5;1;200;20::999", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber( "3.5;1;200;20", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(300)
gg.editAll( "1.0e20", gg.TYPE_FLOAT)
gg.clearResults()
gg.toast("Aimlock")
end

function C()
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber('1,120,403,456;0;1,220,861,952::9', gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
gg.searchNumber('1,120,403,456', gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(3)
gg.editAll('-1,027,211,264', gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("32D;5D;256D;3D;25D;8D;40D:37", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber("40", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(100)
gg.editAll("6", gg.TYPE_DWORD)
gg.toast("Colour")
gg.clearResults()
end

function D()
  gg.toast("Keluar")
  os.exit()
end

while true do
  if gg.isVisible(true) then
    Pharao = 1
    gg.setVisible(false)
  end
  gg.clearResults()
  if Pharao == 1 then
    main()
   end
 end
